# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autofix_commit_msg: "chore: ✏️ automatic pre-commit hook fixes"
  autoupdate_commit_msg: "ci: 👷 update pre-commit CI version"

repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-merge-conflict
        args: [--assume-in-merge]

  # Use the mirror since the main `typos` repo has tags for different
  # sub-packages, which confuses pre-commit when it tries to find the latest
  # version
  - repo: https://github.com/adhtruong/mirrors-typos
    rev: v1.46.2
    hooks:
      - id: typos

  - repo: https://github.com/rvben/rumdl-pre-commit
    rev: v0.1.94
    hooks:
      - id: rumdl-fmt

  - repo: https://github.com/facebook/pyrefly-pre-commit
    # Note: this is the version of the pre-commit hook, NOT the pyrefly version used for type checking.
    rev: 1.2.0.dev1
    hooks:
      - id: pyrefly-check
        name: Pyrefly (type checking)
        # Recommended to do full repo checks, not just on changed files.
        pass_filenames: false
        language: system

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.16
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
