[files]
extend-exclude = [
  "*.html",
  "*.json",
  "*.css",
  ".quarto/*",
  "_site/*",
  "_extensions/*",
  ".coverage-report/*",
  "site_libs/",
  "*.svg",
  # Since it has hashes
  "CHANGELOG.md",
]
