version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: build
      include: scope
    assignees:
      - "lwjohnst86"
