group:
  - files:
      # General
      - source: .github/CODEOWNERS
        dest: .github/CODEOWNERS
      - source: .pre-commit-config.yaml
        dest: .pre-commit-config.yaml
      - source: .editorconfig
        dest: .editorconfig
      - source: .gitignore
        dest: .gitignore
      - source: justfile
        dest: justfile
      - source: poetry.toml
        dest: poetry.toml
      - source: .cz.toml
        dest: .cz.toml
      - source: ruff.toml
        dest: ruff.toml
      - source: LICENSE.md
        dest: LICENSE.md
      - source: .github/pull_request_template.md
        dest: .github/pull_request_template.md

      # Actions
      - source: .github/workflows/add-to-project.yml
        dest: .github/workflows/add-to-project.yml
      - source: .github/workflows/build-package.yml
        dest: .github/workflows/build-package.yml
      - source: .github/workflows/build-website.yml
        dest: .github/workflows/build-website.yml
      - source: .github/workflows/update-version.yml
        dest: .github/workflows/update-version.yml
      - source: .github/_project-dependabot.yml
        dest: .github/dependabot.yml

      # VSCode Settings
      - source: .vscode/
        dest: .vscode/
        deleteOrphaned: true
    repos: |
      seedcase-project/seedcase-sprout
