name: Build package

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    uses: seedcase-project/.github/.github/workflows/reusable-build-python.yml@main
