name: Build website

on:
  push:
    branches:
      - main

# Limit token permissions for security
permissions: read-all

# This is to allow using `gh` CLI
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-website:
    uses: seedcase-project/.github/.github/workflows/reusable-build-docs-with-python.yml@main
    secrets:
      netlify-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
