name: Build package

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      # Config files
      - ".github/**"
      - ".vscode/**"
      - ".gitignore"
      # Documentation
      - "docs/**"
      - "*.md"
      - "*.qmd"
      # Website files
      - _quarto.yml
      - _publish.yml
      - _extensions/**
  push:
    branches:
      - main

jobs:
  build:
    uses: seedcase-project/.github/.github/workflows/reusable-build-python.yml@main
