name: Deploy Demo App

on:
  push:
    branches:
      - main
    paths-ignore:
      # Config files
      - ".github/**"
      - ".vscode/**"
      - ".gitignore"
      # Documentation
      - "docs/**"
      - "*.md"
      - "*.qmd"
      - "justfile"
      # Website files
      - _quarto.yml
      - index.qmd
      - _publish.yml
      - _extensions/**

jobs:
  lint:
    uses: seedcase-project/.github/.github/workflows/lint-python.yml@main

  test:
    uses: seedcase-project/.github/.github/workflows/test.yml@main
    needs: lint
