name: Deploy documentation as website

on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - _quarto.yml
      - index.qmd
      - _publish.yml
      - _extensions/**

jobs:
  build-deploy-docs:
    uses: seedcase-project/.github/.github/workflows/deploy-docs-with-python.yml@main
    secrets:
      netlify-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
