name: Generate SVG from PlantUML

on:
  pull_request:
    paths:
      - '**.puml'

jobs:
  generate-plantuml:
    uses: seedcase-project/.github/.github/workflows/reusable-puml-to-svg.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
