name: Sync files across repos
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.SYNC_FILES_APP_ID }}
          private-key: ${{ secrets.SYNC_FILES_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ steps.app-token.outputs.token }}
          ASSIGNEES: lwjohnst86
          IS_FINE_GRAINED: true
          GIT_USERNAME: github-actions[bot]
          GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          COMMIT_PREFIX: "chore(sync): :hammer: "
          BRANCH_PREFIX: chore
          TEAM_REVIEWERS: admin
