name: Sync files across repos
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    uses: seedcase-project/.github/.github/workflows/reusable-sync-files.yml@main
    with:
      app-id: ${{ vars.SYNC_FILES_APP_ID }}
    secrets:
      sync-files-token: ${{ secrets.SYNC_FILES_TOKEN }}
