name: Update version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    uses: seedcase-project/.github/.github/workflows/reusable-update-python-project-version.yml@main
    with:
      app-id: ${{ vars.UPDATE_VERSION_APP_ID }}
    secrets:
      update-version-gh-token: ${{ secrets.UPDATE_VERSION_TOKEN }}
