name: Update version

on:
  push:
    branches:
      - main

# Limit token permissions for security
permissions: read-all

jobs:
  update-version:
    # Only give permissions for this job.
    permissions:
      contents: write
    uses: seedcase-project/.github/.github/workflows/reusable-update-python-project-version.yml@main
    with:
      app-id: ${{ vars.UPDATE_VERSION_APP_ID }}
    secrets:
      update-version-gh-token: ${{ secrets.UPDATE_VERSION_TOKEN }}
